// ===== Prout Companion — RAG chatbot over "Prout in a Nutshell" (Parts 1-21) + Proutist Economics =====
// Answers are generated by Google Gemini (free tier) via a Netlify Function (netlify/functions/chat.js), which
// keeps the Anthropic API key server-side. This requires an internet connection; if the
// network is unavailable, the app falls back to showing the retrieved source passages directly.

const els = {
  messages: document.getElementById('messages'),
  form: document.getElementById('composer'),
  input: document.getElementById('userInput'),
  sendBtn: document.getElementById('sendBtn'),
  statusPill: document.getElementById('statusPill'),
};

let index = null;
let history = []; // {role, content}
let lastTopicQuery = ''; // last user message that had enough content words to search on well

// Follow-ups like "explain in detail", "why", "what do you mean" carry almost no
// searchable content on their own. If the new message barely tokenizes to anything
// (after stopword removal), treat it as a continuation of the previous topic rather
// than a fresh search query.
function buildSearchQuery(q) {
  const contentWords = tokenize(q); // tokenize() comes from search.js, loaded before this file
  const isVagueFollowUp = contentWords.length < 3 && lastTopicQuery;
  const searchQuery = isVagueFollowUp ? `${lastTopicQuery} ${q}` : q;
  if (!isVagueFollowUp) lastTopicQuery = q;
  return searchQuery;
}

const SYSTEM_PROMPT = `You are Prout Companion, a study guide for P.R. Sarkar's economic and social philosophy PROUT (Progressive Utilization Theory), grounded strictly in the excerpts from "Prout in a Nutshell" (Parts 1-21) and "Proutist Economics" provided to you as CONTEXT below each question.

Rules:
1. Base your answers only on the provided CONTEXT excerpts. Do not invent facts, statistics, or claims not supported by them. If the context doesn't cover something, say so plainly and answer only from what's given.
2. When a question asks for practical, local, real-world planning or application (for example planning a village project, resource use, an economic setup, a cooperative, land or water use), do NOT jump straight to advice. First ask 2-4 short, concrete clarifying questions about the person's specific situation (e.g. location/scale, available resources, local conditions, who is involved) so the guidance can be tailored. Only give detailed guidance after they answer, or if they say they'd rather you proceed with general guidance.
3. When you do give guidance, connect it explicitly to the relevant PROUT principles in the excerpts (e.g. balanced economy, maximum and minimum wage limits, cooperatives, local self-sufficiency, block-level planning) and mention which part/chapter it draws from.
4. Keep answers concise and conversational, like a knowledgeable study companion, not a lecture. Use short paragraphs or brief lists.
5. Never claim certainty beyond what the text supports, and distinguish Sarkar's philosophical/spiritual claims from practical economic proposals when relevant.`;

function addMessage(role, text) {
  const wrap = document.createElement('div');
  wrap.className = `msg ${role}`;
  const bubble = document.createElement('div');
  bubble.className = 'bubble';
  bubble.innerHTML = formatText(text);
  wrap.appendChild(bubble);
  els.messages.appendChild(wrap);
  els.messages.scrollTop = els.messages.scrollHeight;
  return bubble;
}

function formatText(t) {
  return t
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/\n/g, '<br>')
    .replace(/^/, '<p>').replace(/$/, '</p>');
}

function labelFor(c) {
  const n = parseInt(c.part, 10);
  return Number.isNaN(n) ? c.book_title : `Part ${n}`;
}

function addSources(chunks) {
  if (!chunks.length) return;
  const wrap = document.createElement('div');
  wrap.className = 'sources';
  const label = document.createElement('div');
  label.className = 'sources-label';
  label.textContent = 'Sourced from:';
  wrap.appendChild(label);
  const seen = new Set();
  for (const c of chunks) {
    const key = c.part + '|' + c.chapter_title;
    if (seen.has(key)) continue;
    seen.add(key);
    const tag = document.createElement('span');
    tag.className = 'source-tag';
    tag.textContent = `${labelFor(c)} — ${c.chapter_title}`;
    wrap.appendChild(tag);
  }
  els.messages.appendChild(wrap);
  els.messages.scrollTop = els.messages.scrollHeight;
}

function buildContext(chunks) {
  return chunks.map((c, i) =>
    `[Excerpt ${i + 1} — ${labelFor(c)}, "${c.chapter_title}"]\n${c.text}`
  ).join('\n\n');
}

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

const MAX_AUTO_RETRIES = 2;

function isRetryableNetworkError(err) {
  if (!navigator.onLine) return true;
  const msg = (err && err.message ? err.message : String(err)).toLowerCase();
  return ['failed to fetch', 'networkerror', 'timeout', 'upstream ai api error', '502', '503', '504']
    .some(h => msg.includes(h));
}

async function callChatAPI(system, messages, statusFn) {
  let lastErr = null;
  for (let attempt = 0; attempt <= MAX_AUTO_RETRIES; attempt++) {
    try {
      if (attempt > 0) {
        statusFn(`Connection hiccup — retrying (${attempt}/${MAX_AUTO_RETRIES})…`);
        await sleep(700 * attempt);
      }
      const resp = await fetch('/.netlify/functions/chat', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ system, messages }),
      });
      const data = await resp.json().catch(() => ({}));
      if (!resp.ok) {
        throw new Error(data.error || `Request failed (${resp.status})`);
      }
      if (!data.text || !data.text.trim()) {
        throw new Error('Empty response from model');
      }
      return data.text;
    } catch (err) {
      lastErr = err;
      console.error(`Chat API attempt ${attempt} failed:`, err);
      if (!isRetryableNetworkError(err)) break;
    }
  }
  throw lastErr;
}

function addRetryButton(bubble, label, onRetry) {
  const btn = document.createElement('button');
  btn.textContent = label;
  btn.className = 'retry-btn';
  btn.addEventListener('click', () => {
    btn.remove();
    onRetry();
  });
  bubble.appendChild(btn);
  return btn;
}

function showExtractiveFallback(bubble, results) {
  const top = results.slice(0, 3);
  const passages = top.map((c) =>
    `**${labelFor(c)} — ${c.chapter_title}**\n${c.text}`
  ).join('\n\n');
  bubble.innerHTML = formatText(
    "Couldn't reach the AI model (likely no internet connection right now), so here are the most relevant passages directly — no AI summary, but accurate to the source and available offline:\n\n" + passages
  );
}

async function handleSend(e) {
  e.preventDefault();
  const q = els.input.value.trim();
  if (!q) return;
  els.input.value = '';
  els.input.style.height = 'auto';
  els.sendBtn.disabled = true;
  addMessage('user', q);
  await runQuery(q);
  els.sendBtn.disabled = false;
  els.input.focus();
}

async function runQuery(q) {
  const searchQuery = buildSearchQuery(q);
  const results = index.search(searchQuery, 5);
  const context = buildContext(results);

  const typingBubble = addMessage('assistant', '…thinking…');
  typingBubble.parentElement.classList.add('typing');

  const messages = [
    ...history.slice(-4),
    { role: 'user', content: `CONTEXT:\n${context}\n\nQUESTION: ${q}` },
  ];

  try {
    const full = await callChatAPI(SYSTEM_PROMPT, messages, (status) => {
      typingBubble.textContent = status;
    });
    typingBubble.parentElement.classList.remove('typing');
    typingBubble.innerHTML = formatText(full);
    addSources(results);
    history.push({ role: 'user', content: q });
    history.push({ role: 'assistant', content: full });
  } catch (err) {
    typingBubble.parentElement.classList.remove('typing');
    if (isRetryableNetworkError(err)) {
      showExtractiveFallback(typingBubble, results);
      addSources(results);
      addRetryButton(typingBubble, 'Try the AI again', () => runQuery(q));
    } else {
      typingBubble.textContent = 'Something went wrong: ' + err.message;
      addRetryButton(typingBubble, 'Try again', () => runQuery(q));
    }
    console.error(err);
  }
}

els.form.addEventListener('submit', handleSend);

els.input.addEventListener('keydown', (e) => {
  if (e.key === 'Enter' && !e.shiftKey) {
    e.preventDefault();
    els.form.requestSubmit();
  }
});
els.input.addEventListener('input', () => {
  els.input.style.height = 'auto';
  els.input.style.height = Math.min(els.input.scrollHeight, 120) + 'px';
});

function updateOnlineStatus() {
  if (navigator.onLine) {
    els.statusPill.textContent = 'Ready (needs internet)';
    els.statusPill.classList.add('ready');
  } else {
    els.statusPill.textContent = 'Offline — will show source passages only';
    els.statusPill.classList.remove('ready');
  }
}
window.addEventListener('online', updateOnlineStatus);
window.addEventListener('offline', updateOnlineStatus);

document.addEventListener('DOMContentLoaded', () => {
  index = getProutIndex();
  updateOnlineStatus();
  els.input.disabled = false;
  els.sendBtn.disabled = false;
  els.input.focus();
});
